# name: Testes e Deploy

# on: 
#   push:
#     branches: [ api ]

# jobs:
#   pylint: # Verifica erros no código 
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up do Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.x

#     - name: Instalando dependencias
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint

#     - name: Análise do código com Pylint
#       run: |
#         pylint $(git ls-files '*.py')

#   deploy_job: # Faz deploy no servidor Azure
#     runs-on: ubuntu-latest
#     name: deploy
#     # needs: pylint # Só será executado se o Pylint for aprovado
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Deploy do Arquivo
#         uses: wlixcc/SFTP-Deploy-Action@v1.0
#         with:
#           username: ${{ secrets.sftp_user }}
#           server: ${{ secrets.sftp_host }}
#           port: ${{ secrets.sftp_port }}
#           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#           local_path: './*' # Arquivo que será alterado
#           remote_path: '/home/iotuser/plataforma/dados/' # Pasta de destino
#           args: '-o ConnectTimeout=5'